### ISSUE TITLE
Can not launch

### ISSUE THREAD

**Issue by xjoscx** [onlfait/VisualSFM#1]
Hi,
I tried to install VisualSFM.
I downloaded the Program from http://ccwu.me/vsfm/.
But everytime I try to open it i will get an 0xc000007b error.
I do not know what to do.
Already tried to reinstall Visual C++, FrameNET, DirectX and XINPUT1_3.
I am happy about every suggestion.

**Comment by lautr3k** [comment]
Go to https://github.com/alicevision/meshroom ;)
